const KOR = {
	STOCK_DIARY: '주식 다이어리',
	OK: '확인',
	CANCEL: '취소',
	SAVE: '저장',
	CLOSE: '닫기',
	CLEAR: '초기화',
	REGIST: '등록',
	DELETE: '삭제',
	ADD: '추가',
	EDIT: '편집',
	UPDATE: '수정',
	SETTING: '설정',
	ALARM: '알림',
	WARNING: '경고',
	ERROR: '에러',
	AUTH: '권한',
	NEXT: '다음',
	PREV: '이전',
	TYPE: '타입',
	SELECTION: '선택하세요',
	ALL: '전체',
	NUM: '번호',
	URL: 'URL',
	ORDER: '순번',
	KIND: '종류',
	DESC: '설명',
	STATUS: '상태',
	CTIME: '등록일',
	UTIME: '수정일',
	TOTAL: '총계',
	MORE: '더보기',
	NONE: 'N/A',
	MANAGEMENT: '관리',
	MORE_INFO: '추가정보',
	SELECT_FILE: '파일선택',
	NOIMAGE: 'NO IMAGE!',
	YES: 'YES',
	NO: 'NO',
	FIRST: '처음',
	LAST: '끝',
	WEEK: '주일',
	YEAR: '년',
	MONTH: '월',
	DAY: '일',
	DATE: '날자',
	COUNT: '개',
	VISIBLE: '사용',
	THUMB: '썸네일',
	TITLE: '제목',
	IN_TITLE: '제목을 입력하세요.',
	IN_VALUE: '값을 입력하세요.',
	IN_DATE: '날자를 입력하세요.',
	IN_NUMBER: '숫자를 입력하세요.',
	CHECK_DUP: '중복체크',
	CHECK_OK: '확인되었습니다',
	CHECK_CONN: '연결확인',
	BUY: '매수',
	SELL: '매도',
	KEEP: '보유',
	NO_KEEP: '미보유',
	FAVORIT_KEEP: '관심종목',
	NEXT_KEEP: '투자예정',
	YEAR_SONIC: '연수익',
	YEAR_SONIC_DESC: '1년 기준 수익율',
	MAX_PER_SONIC: '최대투자금대비',
	CALC: '목표계산기',
	CALC_PRICE: '목표율(가격)',
	CALC_CUSTOM: '목표율(직접입력)',
	KEEP_SISE: '예상',
	SELL_SISE: '예상수익',
	CURRENT_SELL_SISE: '현재가 매도시',
	WON: '원',
	JU: '주',
	MAN: '만',
	MANJU: '만주',
	SISE: '현재가',
	SISE_END: '종가',
	STOCK_KIND: '종목',
	STOCK_CODE: '종목코드',
	UNIT: '단위',
	MANWON: '만원',
	SONIC: '손익',
	SONIC_UP: '손익',
	SONIC_DN: '손절',
	TRADE: '거래',
	COST: '단가',
	PRICE: '금액',
	PRICE_SUM: '누적',
	START_DATE: '시작일',
	END_DATE: '종료일',
	ID: '아이디',
	PASSWORD: '비밀번호',
	MEMBERSHIP: '회원가입',
	SONIC_PER: '수익율',
	KEEP_DATE: '보유일',
	TRADE_LIST: '거래내역',
	KEEP_STOCK: '보유종목',
	KEEP_LIST: '보유현황',
	MIN_VALUE: '최소값은',
	MAX_VALUE: '최대값은',
	IS_SUFFIX: '입니다. ',
	MEM_COUNT: '명',
	YESTERDAY: '어제',
	TODAY: '오늘',
	TOWEEK: '이번주',
	TOMONTH: '이번달',
	SELECT_IS_FILE: '파일을 선택하세요',
	PHONE: '연락처',
	DIVIDEND: '배당',
	DIVIDEND_HISTORY: '배당 내역',
	PER_SONIC: '종목별 손익',
	SISE_SONIC: '예상손익',
	CLOSE_STOCK: '상장폐지',
	UP_SORT: '오름차순',
	DOWN_SORT: '내림차순',
	ECOST: '등락',
	KOSPI: '코스피',
	KOSDAQ: '코스닥',
	SUM: '합계',
	TAX: '제세금',
	MORE_IN: '요약보기',
	MORE_OUT: '전체보기',
	ASSET: '투자금',
	EVALUATION: '평가금액',
	DEPOSIT: '예수금',
	ACC_ASSET: '누적투자',
	INVESTMENT_STATUS: '투자 현황',
	ASSETVSEVALUATION: '투자금 VS 평가금액',

	NO_SERVICE: '서비스 준비중',

	PLEASE_INPUT: '입력하세요',
	PLEASE_SELECT: '선택하세요',

	REGISTERED: '등록되었습니다.',
	UPDATED: '저장되었습니다.',
	DELETEED: '삭제되었습니다.',

	NODATA: '표시할 데이터가 없습니다.',
	SUCCESS: '처리되었습니다.',
	FAILUER: '오류가 발생했습니다.',
	DUP_ITEM: '이미 등록된 항목입니다.',
	ONLY_NUMBER: '숫자(0-9)만 입력 가능합니다.',
	WANT_TO_DELETE: '삭제하시겠습니까?',
	WANT_TO_REFRESH: '갱신하시겠습니까?',
	WANT_TO_UPDATE_NAVER: '네이버(추정) 데이터로 업데이트 하시겠습니까?',

	ERROR_PROBLEM: '문제가 발생했습니다!',
	ERROR_UNKNOWN: '알 수 없는 오류가 발생했습니다.',
	ERROR_NETWORK: '네트워크 오류가 발생했어요. 인터넷 연결을 확인해주세요.',
	ERROR_NOT_FOUND: '요청한 데이터를 찾을 수 없습니다.',

	NAME: '이름',
	STOCKNAME: '주식명',
	KEEP_RATE: '보유율',
	KEEP_COST: '보유금액',
	STOCK_COUNT: '주식수',
	BUY_AND_SELL: '매수/매도',
	ACC_COST: '평균단가',
	NO_HISTORY: '내역없음',

	CAPITAL: '자본',
	VALUATION: '평가금액',
	SONIC_COST: '손익금액',
	SONIC_RATE: '손익율',

	PER_CODES: '종목별',
	PER_YEARS: '연도별',
	PER_MONTHS: '월별',
	PER_DIVIDEND: '배당내역',
	PER_DAYS: '일별',
	INVEST: '가치투자',

	PER_OPEN: '상장종목',
	PER_CLOSE: '상폐종목',

	INVESTMENT_SMIULATION: '투자 시뮬레이션',
	INVESTMENT_FINAL: '최종 평가액',
	INVESTMENT_SONIC: '순이익',
	INVESTMENT_IN: '누적 투자금',

	BUCKETLIST: {
		PRINCIPAL: '원금',
		RATE: '연이율(%)',
		START_YEARS: '시작년도',
		YEARS: '투자기간(년)',
		ANNUAL: '추가투자액',
		CHART: '자산성장곡선(추가투자 포함 vs 미포함)',
		TABLE: '연도별 상세',
		PAGE: '고유번호',
		TARGET_TABLE: '연도별 상세(목표달성)',
	},

	MENU: {
		MAINBOARD: '메인',
		DASHBOARD: '대시보드',
		DIARY: '다이어리',
		MARKET: '종목검색',
		RESEARCH: '투자조사',
		PROFIT: '투자손익',
		INVEST: '가치투자',
		DIVIDEND: '배당',
		ASSET: '투자금',
		DEPOSIT: '예수금',
		MENUS: '메뉴',
		MORE: '더보기',

		BANKING: '잔고',
		BUCKET: '버킷',
	},

	STOCK_TITLE: '주식(종목)명',
	STOCK_APPEND: '종목 추가',

	BUY_DATE: '매수일',
	SELL_DATE: '매도일',
	BUY_COST: '매수단가',
	SELL_COST: '매도단가',
	INPUT_SEARCH: '종목명 또는 코드 입력',
	SELECT_SEARCH: '추가할 종목 선택하세요.',
	MARKET: '거래소',
	UPDATE_TIME: '업데이트 일시',
	NO_DATA: '내역이 없습니다.',

	STOCK_PER_COST: '주당금액',
	DIVIDEND_SUM: '배당금',
	DIVIDEND_TOTAL: '배당금(세후)',

	EMPTY_INVESTMENT: '년도 평가기준 설정',
	ROE: '자본이익율(ROE)',
	STOCKS_COUNT: '발행주식',
	BASE_YEAR: '기준년도',
	EQUITY: '자본(지배주주)',
	// BS: '자기자본(BS)',
	EXCESS_PROFIT: '초과이익',
	SHARE_VALUE: '주주가치',
	PER_VALUE: '주당가치',
	BASE_RATE: '기준평가율',
	BASE_07: '평가율(W0.7)',
	BASE_08: '평가율(W0.8)',
	BASE_09: '평가율(W0.9)',
	BASE_10: '평가율(W1.0)',

	HEND_WRITING: '수기',
	
	PRICE_BEFORE_TAX: '금액(세전)',
	PRICE_AFTER_TAX: '금액(세후)',
	PRICE_TAX: '세금',

	EXIST_DATA_INVEST: '년도 데이터는 등록 되어 있습니다.',


	MAINBOARD: {
		KEEP: '보유 상위',
		SONIC_TOP: '평가손익(상위)',
		SONIC_BOTTOM: '평가손실(상위)',
		SONIC_BUY_TOP: '매수 손익율(상위)',
		SONIC_BUY_BOTTOM: '매수 손실율(상위)',
		SELL: '최근 매도',
		BUY: '최근 매수',
		SUMMARY: '요약 보기',
	},

	PROFIT_TABLE: {
		YEAR: '년월',
		NAME: '종목명',
		CODE: '종목코드',
		SDATE: '매수일',
		EDATE: '매도일',
		SPRICE: '매수금',
		EPRICE: '매도금',
		SONICRATE: '손익율[%]',
		YSONICRATE: '년손익율[%]',
		SONIC: '손익',
	},

	BUCKET_TABLE: {
		YEAR: '연도',
		START: '연초 금액',
		AFTER_GROWTH: '15% 적용 후',
		CONTRIBUTION: '추가금',		
		TOTAL: '연말 총액',
		NOT_ADDED: '추가 없음',
		INTEREST: '당해 이자',

		TARGET: '목표 금액',
		RESULT: '실현 결과',
	},

	RESEARCH_TABLE: {
		NAME: '주식명',
		COUNT: '발행주식수',
		ROE: 'ROE',
		PROFIT: '당기순이익',
		ASSET: '자본',
		STIME: '시세일시',
		SHARE_RATE: '가치',
		SISE: '시세',
		SHARE: '목표값',
	}
};

export const ST = KOR;
