const KOR = {
	OK: '확인',
	CANCEL: '취소',
	SAVE: '저장',
	CLOSE: '닫기',
	CLEAR: '초기화',
	REGIST: '등록',
	DELETE: '삭제',
	ADD: '추가',
	EDIT: '편집',
	UPDATE: '수정',
	SETTING: '설정',
	ALARM: '알림',
	WARNING: '경고',
	ERROR: '에러',
	AUTH: '권한',
	NEXT: '다음',
	PREV: '이전',
	TYPE: '타입',
	SELECTION: '선택하세요',
	ALL: '전체',
	NUM: '번호',
	URL: 'URL',
	ORDER: '순번',
	KIND: '종류',
	DESC: '설명',
	STATUS: '상태',
	CTIME: '등록일',
	UTIME: '수정일',
	TOTAL: 'TOTAL',
	MORE: '더보기',
	NONE: 'N/A',
	MANAGEMENT: '관리',
	MORE_INFO: '추가정보',
	SELECT_FILE: '파일선택',
	NOIMAGE: 'NO IMAGE!',
	YES: 'YES',
	NO: 'NO',
	FIRST: '처음',
	LAST: '끝',
	WEEK: '주일',
	YEAR: '년',
	MONTH: '월',
	DAY: '일',
	DATE: '날자',
	COUNT: '개',
	VISIBLE: '사용',
	THUMB: '썸네일',
	TITLE: '제목',
	IN_TITLE: '제목을 입력하세요.',
	IN_VALUE: '값을 입력하세요.',
	CHECK_DUP: '중복체크',
	CHECK_OK: '확인되었습니다',
	CHECK_CONN: '연결확인',
	BUY: '매수',
	SELL: '매도',
	KEEP: '보유',
	YEAR_SONIC: '연수익',
	YEAR_SONIC_DESC: '1년 기준 수익율',
	MAX_PER_SONIC: '최대투자금대비',
	CALC: '목표계산기',
	CALC_PRICE: '목표율(가격)',
	CALC_CUSTOM: '목표율(직접입력)',
	KEEP_SISE: '예상',
	SELL_SISE: '예상수익',
	CURRENT_SELL_SISE: '현재가 매도시',
	WON: '원',
	JU: '주',
	MAN: '만',
	MANJU: '만주',
	SISE: '현재가',
	SISE_END: '종가',
	STOCK_KIND: '종목',
	STOCK_CODE: '종목코드',
	UNIT: '단위',
	MANWON: '만원',
	SONIC: '손익',
	SONIC_UP: '이익',
	SONIC_DN: '손해',
	TRADE: '거래',
	COST: '단가',
	PRICE: '금액',
	PRICE_SUM: '누적',
	START_DATE: '시작일',
	END_DATE: '종료일',
	ID: '아이디',
	PASSWORD: '비밀번호',
	MEMBERSHIP: '회원가입',
	SONIC_PER: '수익율',
	KEEP_DATE: '보유일',
	TRADE_LIST: '거래내역',
	KEEP_STOCK: '보유종목',
	KEEP_LIST: '보유현황',
	MIN_VALUE: '최소값은',
	MAX_VALUE: '최대값은',
	IS_SUFFIX: '입니다. ',
	MEM_COUNT: '명',
	YESTERDAY: '어제',
	TODAY: '오늘',
	TOWEEK: '이번주',
	TOMONTH: '이번달',
	SELECT_IS_FILE: '파일을 선택하세요',
	PHONE: '연락처',
	SHARE: '배당',
	PER_SONIC: '종목별 손익',
	SISE_SONIC: '예상손익',
	CLOSE_STOCK: '상장폐지',
	UP_SORT: '오름차순',
	DOWN_SORT: '내림차순',
	ECOST: '등락',

	NO_SERVICE: '서비스 준비중',

	PLEASE_INPUT: '입력하세요',
	PLEASE_SELECT: '선택하세요',

	SAVEED: '저장되었습니다.',
	EDITED: '수정되었습니다.',
	DELETEED: '삭제되었습니다.',
	NODATA: '표시할 데이터가 없습니다.',
	SUCCESS: '처리되었습니다.',
	FAILUER: '오류가 발생했습니다.',
	DUP_ITEM: '이미 등록된 항목입니다.',
	ONLY_NUMBER: '숫자(0-9)만 입력 가능합니다.',
	WANT_TO_DELETE: '삭제하시겠습니까?',

	ERROR_PROBLEM: '문제가 발생했습니다!',
	ERROR_UNKNOWN: '알 수 없는 오류가 발생했습니다.',
	ERROR_NETWORK: '네트워크 오류가 발생했어요. 인터넷 연결을 확인해주세요.',
	ERROR_NOT_FOUND: '요청한 데이터를 찾을 수 없습니다.',

	NAME: '이름',
	STOCKNAME: '주식명',
	KEEP_RATE: '보유율',
	KEEP_COST: '보유금액',
	STOCK_COUNT: '주식수',
	BUY_AND_SELL: '매수/매도',
	ACC_COST: '평균단가',
	NO_HISTORY: '내역없음',

	CAPITAL: '자본',
	AT_MARKET_PRICE: '시세매도시',
	SONIC_COST: '손익금액',
	SONIC_RATE: '손익율',

	PER_CODES: '종목별',
	PER_MONTHS: '월별',
	PER_DAYS: '일별',

	MENU: {
		DASHBOARD: '메인',
		MARKET: '종목검색',
		PROFIT: '투자손익',
		INVEST: '가치투자',

		BANKING: '잔고',
		BUCKET: '버킷',
	},

	// DASHBOARD: {
	// 	ADD: '종목 추가',

	// 	CHART_A: '보유종목비율',
	// 	CHART_B: '보유종목금액',
	// 	CHART_C: '종목별손익',
	// 	CHART_D: '종목별예상손익',
	// 	RATE: '보유비율',
	// 	UPDATE: '종목 수정',
	// 	NAME: '주식(종목)명',
	// 	NAVER: 'NAVER',
	// 	DAUM: 'DAUM',
	// 	HOME: 'HOMEPAGE',
	// 	SELL: '매도',
	// 	BUY: '매수',
	// 	TOTAL: '현재가매도시',
	// 	MAX_SUIC: '최대수익',
	// 	MIN_SUIC: '최저수익',

	// 	H: {
	// 		NAME: '주식(종목) 명은 최대 50글자입니다.',
	// 	},
	// },

	// PROFIT: {
	// 	YEARMONTH: '년월',
	// 	NAME: '종목명',
	// 	CODE: '종목코드',
	// 	SDATE: '매수일',
	// 	EDATE: '매도일',
	// 	SPRICE: '매수금',
	// 	EPRICE: '매도금',
	// 	SONICRATE: '손익율[%]',
	// 	YSONICRATE: '년손익율[%]',
	// },

	// DAILY: {
	// 	DAY: '날짜',
	// 	COST: '종가',
	// 	PREVRATE: '전일비',
	// 	CVAL: '대비',
	// 	UPRATE: '등락률',
	// 	COUNT: '거래량',
	// 	ACCUM: '누적량',
	// 	ORG: '기관',
	// 	FRN: '외인',
	// 	ALL: '전체',
	// 	REST: '그외',
	// 	WEEK: '5일',
	// 	TEN: '10일',
	// 	MONTH: '30일',
	// 	FROM: '부터',
	// 	MONTH3: '3개월',
	// 	MONTH6: '5개월',
	// 	YEAR1: '1년',
	// 	YEAR2: '2년',
	// 	YEAR3: '3년',
	// 	YEAR5: '5년',
	// 	YEAR10: '10년',
	// 	FRN_ORG: '외인/기관 거래량',
	// 	COST_RATE: '일별/누적 등락액',
	// },

	// MARKET: {
	// 	COMP_INFO: '기업개요',
	// 	INPUT_SEARCH: '종목명 또는 코드 입력',
	// },

	// BUCKET: {
	// 	MONTH: '월단위',
	// 	YEAR: '년단위',
	// 	TH_YEAR: '년월',
	// 	TH_BASE: '투자금',
	// 	TH_SAVE: '추가',
	// 	TH_RATE: '이율',
	// 	TH_MSONIC: '목표수익',
	// 	TH_RSONIC: '실제수익',
	// 	TH_PRICE: '소계',
	// 	INIT_PRICE: '초기투자금',
	// 	FROM: ({
	// 		start,
	// 		year,
	// 		save,
	// 		rate,
	// 		base,
	// 	}: {
	// 		start: string;
	// 		year: string;
	// 		save: string;
	// 		rate: string;
	// 		base: string;
	// 	}) => `${start}월 부터 ${year}년간 매월 ${save}원씩 추가하고 년 ${rate}%의 수익이 날경우(초기 투자금 = ${base})`,
	// 	MODAL_A: '시작 년월일',
	// 	MODAL_B: '초기 투자금',
	// 	MODAL_C: '매월 추가금',
	// 	MODAL_D: '기간(년)',
	// 	MODAL_E: '수익율(%)',
	// 	DESC_BASE: '년(월) 시작시점의 투자 원금.',
	// 	DESC_SAVE: '매월 일정한 저축성 투자 추가금.',
	// 	DESC_RATE: '투자금에 대한 예상(목표) 이율(%).',
	// 	DESC_SONIC: '투자금 * 이율(%)',
	// 	DESC_PRICE: '투자금 + 추가금 + 수익.',
	// },
};

export const ST = KOR;
