export const URL = {
	ROOT: '/',

	MAIN: '/main',
	DASHBOARD: '/dashboard',
	MYSTOCK: '/mystock',
	DIARY: '/diary',
	MARKET: '/market',
	RESEARCH: '/research',
	ASSET: '/asset',
	DEPOSIT: '/deposit',
	PROFIT: '/profit',
	DAILY: '/daily',
	DIVIDEND: '/dividend',
	INVEST: '/invest',
	BUCKET: '/bucket',
	STATISTIC: '/statistic',
	SELL: '/sell',
	BUY: '/buy',
	STOCKS: '/stocks',
	MEMUS: '/menus',
	
	REST: {
		NAVER: 'https://finance.naver.com/item/main.nhn',
		DAUM: 'https://finance.daum.net/quotes/',
		FNGUIDE: (code: string) =>
			`https://comp.fnguide.com/SVO2/ASP/SVD_Main.asp?pGB=1&gicode=${code}&cID=&MenuYn=Y&ReportGB=&NewMenuID=101&stkGb=701`,
	},
};

const API_ROOT = '/api/v1';

export const API = {
	MAINBOARD: `${API_ROOT}/main`,
	DASHBOARD: `${API_ROOT}/dashboard`,
	DASHBOARD_POSITION: `${API_ROOT}/dashboard/position`,
	DIARY: `${API_ROOT}/diary`,
	MYSTOCK: `${API_ROOT}/mystock`,
	MYSTOCK_SISE: `${API_ROOT}/mystock/sise`,
	MYSTOCK_BUY: `${API_ROOT}/mystock/buy`,
	MYSTOCK_SELL: `${API_ROOT}/mystock/sell`,
	STOCK: `${API_ROOT}/stock`,
	MARKET: `${API_ROOT}/market`,
	MARKET_SEARCH: `${API_ROOT}/market/search`,
	MARKET_SISE: `${API_ROOT}/market/sise`,
	MARKET_COUNT: `${API_ROOT}/market/vcount`,
	INVEST: `${API_ROOT}/invest`,
	INVEST_YEAR: `${API_ROOT}/invest/year`,
	INVEST_BOOKMARK: `${API_ROOT}/invest/bookmark`,
	INVEST_CLEAR: `${API_ROOT}/invest/clear`,
	INVEST_REFRESH: `${API_ROOT}/invest/refresh`,
	INVEST_REPORT: `${API_ROOT}/invest/report`,
	INVEST_DART: `${API_ROOT}/invest/dart`,
	// INVEST_UPDATE_BY_NAVER: `${API_ROOT}/invest/naver`,
	PROFIT: `${API_ROOT}/profit`,
	PROFIT_YEARS: `${API_ROOT}/profit/years`,
	DIVIDEND: `${API_ROOT}/dividend`,
	ASSET: `${API_ROOT}/asset`,
	EVALUATION: `${API_ROOT}/evaluation`,
	DEPOSIT: `${API_ROOT}/deposit`,
	BUCKET: `${API_ROOT}/bucket`,
	APP: `${API_ROOT}/app`,
	APP_CONFIG: `${API_ROOT}/app/config`,
	RESEARCH: `${API_ROOT}/research`,
	RESEARCH_DETAIL: `${API_ROOT}/research/detail`,
	RESEARCH_YEAR: `${API_ROOT}/research/year`,
	RESEARCH_UPDATE_BY_NAVER: `${API_ROOT}/research/naver`,
	RESEARCH_SISE: `${API_ROOT}/research/sise`,
	RESEARCH_NAVER: `${API_ROOT}/research/naver`,
	RESEARCH_REFRESH: `${API_ROOT}/research/refresh`, 
	STATISTIC: `${API_ROOT}/statistic`,
};
