import * as OBJ from './default.config';

const KOR = {
	...OBJ.ST,

	START_YEAR: '2019',
	COMPANY_NAME: 'NURISTOCK',
	COPYRIGHT: `COPYRIGHT© 2020 NURIO ALL RIGHT RESERVED`,

	BUY: '매수',
	SELL: '매도',
	KEEP: '보유',
	YEAR_SONIC: '연수익',
	YEAR_SONIC_DESC: '1년 기준 수익율',
	MAX_PER_SONIC: '최대투자금대비',
	CALC: '목표계산기',
	CALC_PRICE: '목표율(가격)',
	CALC_CUSTOM: '목표율(직접입력)',
	KEEP_SISE: '예상',
	SELL_SISE: '예상수익',
	CURRENT_SELL_SISE: '현재가 매도시',
	WON: '원',
	JU: '주',
	MAN: '만',
	MANJU: '만주',
	SISE: '현재가',
	SISE_END: '종가',
	STOCK_KIND: '종목',
	STOCK_CODE: '종목코드',
	TOTAL: '총',
	PREV: '이전',
	NEXT: '다음',
	FIRST: '처음',
	LAST: '끝',
	UNIT: '단위',
	MANWON: '만원',
	SONIC: '손익',
	SONIC_UP: '이익',
	SONIC_DN: '손해',
	TRADE: '거래',
	YEAR: '년',
	MONTH: '월',
	DAY: '일',
	COST: '단가',
	DATE: '날자',
	NUM: '개수',
	COUNT: '회',
	PRICE: '금액',
	PRICE_SUM: '누적',
	OK: '확인',
	CANCEL: '취소',
	SAVE: '저장',
	DELETE: '삭제',
	ADD: '추가',
	EDIT: '편집',
	UPDATE: '수정',
	ALARM: '알림',
	WARNING: '경고',
	ERROR: '에러',
	START_DATE: '시작일',
	END_DATE: '종료일',
	ID: '아이디',
	PASSWORD: '비밀번호',
	MEMBERSHIP: '회원가입',
	SONIC_PER: '수익율',
	KEEP_DATE: '보유일',
	TRADE_LIST: '거래내역',
	KEEP_STOCK: '보유종목',
	KEEP_LIST: '보유현황',
	MIN_VALUE: '최소값은',
	MAX_VALUE: '최대값은',
	IS_SUFFIX: '입니다. ',
	MEM_COUNT: '명',
	YESTERDAY: '어제',
	TODAY: '오늘',
	TOWEEK: '이번주',
	TOMONTH: '이번달',
	SELECT_FILE: '파일선택',
	SELECT_IS_FILE: '파일을 선택하세요',
	PHONE: '연락처',
	SHARE: '배당',
	NONE: '없음',
	PER_SONIC: '종목별 손익',
	SISE_SONIC: '예상손익',
	CLOSE_STOCK: '상장폐지',
	UP_SORT: '오름차순',
	DOWN_SORT: '내림차순',
	ECOST: '등락',

	LOGIN: {
		TITLE: '로그인',
		NOTI_LOGIN: '로그인 정보를 정확히 입력하세요.',
		PASSWORD_FIND: '비밀번호 찾기',
		LOGOUT: '로그아웃',
	},

	MEMBER: {
		TITLE: '회원가입',
		ID_NOTI: '아이디를 입력하세요.',
		PASSWORD_NOTI: '비밀번호가 일치하지 않습니다.',
		DUPUSERID: '중복된 사용자 ID 입니다.',
		MEMBER_OK: '회원가입을 축하드립니다.\n로그인 화면으로 이동합니다.',
		DESC: "'회원가입'을 클릭하면 서비스약관 및 개인정보보호 정책에 동의하는 것입니다.",
		ID: '아이디(email@email.com)',
		PASSWORD_CHECK: '비밀번호 확인',
		NAME: '사용자 이름',

		H: {
			ID: '이메일 형식의 아이디를 입력하세요.',
			PASSWORD: '영문/숫자를 조합하여 8~12자로 입력하세요',
			PHONE: '[-]없이 입력하세요(예:01012341234)',
		},
	},

	MYPAGE: {
		STOCKNAME: '주식명',
		RATE: '보유율',
		PRICE: '보유금액',
		SONIC: '손익금액',
		SONIC_SISE: '예상손익',
		NAME: '이름',
		SONICRATE: '손익율',
	},

	MYSTOCK: {
		CHART_A: '주식수',
		CHART_B: '보유금액',
		CHART_C: '평균단가',
		CHART_D: '손익',
		CHART_E: '매수/매도',
		COUNT: '주식수',
	},

	DASHBOARD: {
		CHART_A: '보유종목비율',
		CHART_B: '보유종목금액',
		CHART_C: '종목별손익',
		CHART_D: '종목별예상손익',
		RATE: '보유비율',
		COST: '보유금액',
		ADD: '종목 추가',
		UPDATE: '종목 수정',
		NAME: '주식(종목)명',
		NAVER: 'NAVER',
		DAUM: 'DAUM',
		HOME: 'HOMEPAGE',
		NO_HISTORY: '내역없음',
		TOT: {
			SELL: '매도',
			BUY: '매수',
			KEEP: '보유금액',
			SONIC_SISE: '예상손익',
			SONIC: '손익',
			TOTAL: '현재가매도시',
			SONIC_PER: '손익율',
		},
		MAX_SUIC: '최대수익',
		MIN_SUIC: '최저수익',

		H: {
			NAME: '주식(종목) 명은 최대 50글자입니다.',
		},
	},

	DAILY: {
		DAY: '날짜',
		COST: '종가',
		PREVRATE: '전일비',
		CVAL: '대비',
		UPRATE: '등락률',
		COUNT: '거래량',
		ACCUM: '누적량',
		ACCRATE: '보유율',
		ORG: '기관',
		FRN: '외인',
		ALL: '전체',
		REST: '그외',
		WEEK: '5일',
		TEN: '10일',
		MONTH: '30일',
		FROM: '부터',
		MONTH3: '3개월',
		MONTH6: '5개월',
		YEAR1: '1년',
		YEAR2: '2년',
		YEAR3: '3년',
		YEAR5: '5년',
		YEAR10: '10년',
		FRN_ORG: '외인/기관 거래량',
		COST_RATE: '일별/누적 등락액',
	},

	MENU: {
		DASHBOARD: '메인',
		MARKET: '국내',
		BANKING: '잔고',
		PROFIT: '손익',
		INVEST: '종목발굴',
		DAILY: '일별종가',
		BUCKET: '버킷',
	},

	MARKET: {
		COMP_INFO: '기업개요',
		INPUT_SEARCH: '종목명 또는 코드 입력',
	},

	BANK: {
		TOTAL: '총액',
		YEAR: '년월',
		TOTAL_DESC: '(투자금+손익)',
		REST: '투자금',
		REST_DESC: '(입금-출금)',
		SONIC_DESC: '(손익+배당)',
		IN: '입금',
		OUT: '출금',
		DEPOSIT: '예수금',
		MEMO: '메모',
		SISE: '현재가매도시',
		SISE_DESC: '(현재가매도시)',
		PRICE: '잔고',
		AVERAGE: '월평균',
		CHART_A: '입출금내역',
		CHART_B: '월별잔고',
	},

	BUCKET: {
		MONTH: '월단위',
		YEAR: '년단위',
		TH_YEAR: '년월',
		TH_BASE: '투자금',
		TH_SAVE: '추가',
		TH_RATE: '이율',
		TH_MSONIC: '목표수익',
		TH_RSONIC: '실제수익',
		TH_PRICE: '소계',
		INIT_PRICE: '초기투자금',
		FROM: ({
			start,
			year,
			save,
			rate,
			base,
		}: {
			start: string;
			year: string;
			save: string;
			rate: string;
			base: string;
		}) =>
			`${start}월 부터 ${year}년간 매월 ${save}원씩 추가하고 년 ${rate}%의 수익이 날경우(초기 투자금 = ${base})`,
		MODAL_A: '시작 년월일',
		MODAL_B: '초기 투자금',
		MODAL_C: '매월 추가금',
		MODAL_D: '기간(년)',
		MODAL_E: '수익율(%)',
		DESC_BASE: '년(월) 시작시점의 투자 원금.',
		DESC_SAVE: '매월 일정한 저축성 투자 추가금.',
		DESC_RATE: '투자금에 대한 예상(목표) 이율(%).',
		DESC_SONIC: '투자금 * 이율(%)',
		DESC_PRICE: '투자금 + 추가금 + 수익.',
	},

	PROFIT: {
		YEAR: '년도',
		CODES: '종목별',
		MONTHS: '월별',
		DAYS: '일별',
		ALL: '전체',
		YEARMONTH: '년월',
		NAME: '종목명',
		CODE: '종목코드',
		SDATE: '매수일',
		EDATE: '매도일',
		SPRICE: '매수금',
		EPRICE: '매도금',
		SONICRATE: '손익율[%]',
		YSONICRATE: '년손익율[%]',
		SONIC: '손익',
	},

	WORK: {
		TITLE: '일정 관리',
		NEW_H: '일정을 등록하시려면',
		NEW_C: '여기를',
		NEW_F: '클릭하세요',
	},

	TASK: {
		TITLE: '태스크',
		START: '시작일',
		END: '종료일',
		NAME: '태스크 명',
		PARENT_NODE: '부모 노드',
		DATE: '기간',
		PROGRESS: '진행율',
		ADD: '태스크 추가',
		UPDATE: '태스크 수정',
		GROUP_EDIT: '그룹 수정',
		GROUP_DELETE: '그룹 삭제',

		G: {
			NAME: '태스크 명을 입력하세요',
			START: '태스크 시작일',
			END: '태스크 종료일',
			PROGRESS: '진행율(0 ~ 100%)을 입력하세요',
		},

		H: {
			NAME: '태스크 명은 최대 50글자입니다.',
		},
	},

	ALERT: {
		NO_INPUT_VALUE: '값을 입력하세요',
	},

	Q: {
		DELETE: '정말로 삭제하시겠습니까?',
		STOCK_DELETE: '거래내역이 있습니다. 그래도 삭제하시겠습니까?',
	},

	NOTI: {
		START_DATE: '시작일보다 빠를수 없습니다',
		SAVE: '저장되었습니다.',
		EDIT: '수정되었습니다.',
		DELETE: '삭제되었습니다.',
		NODATA: '표시할 데이터가 없습니다.',
		SUCCESS: '정상적으로 처리되었습니다.',
		FAILUER: '오류가 발생했습니다.',
		DUP_ITEM: '이미 등록된 항목입니다.',
		DUP_MEMBER: '이미 등록된 아이디 입니다.',
	},
};

export const ST = KOR;
